trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: BuildWithMaven
  jobs:
  - job: MavenBuild
    displayName: 'Build with Maven'
    steps:
    - script: |
        cd java-maven  # Navigate to the directory containing your pom.xml for Maven
        mvn clean package
      displayName: 'Maven Build'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'java-maven/target'  # Adjust the path to your Maven build output
        ArtifactName: 'maven-build'
        publishLocation: 'Container'

