trigger:
- master

parameters:
- name: solutionPath
  type: string
  default: '**/*.sln'

stages:
- stage: BuildAndPublish
  displayName: 'Build and Publish Stage'
  jobs:
  - job: BuildAndPublish
    displayName: 'Build and Publish ASP.NET App'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@0

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '${{ parameters.solutionPath }}'

    - task: VSBuild@1
      inputs:
        solution: '${{ parameters.solutionPath }}'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: 'Any CPU'
        configuration: 'Release'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish build artifacts'
      inputs:
        PathtoPublish: $(build.artifactstagingdirectory)
        ArtifactName: 'PublishBuildArtifacts'
