trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
parameters:
- name: applicationPath
  type: string
  default: 'java-ant'

stages:
- stage: BuildWithAnt
  jobs:
  - job: AntBuild
    displayName: 'Build with Ant'
    steps:
    - script: |
        cd ${{parameters.applicationPath}}  # Navigate to the directory containing your build.xml for Ant
        ant build  # Replace 'build' with your Ant target
      displayName: 'Ant Build'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '${{parameters.applicationPath}}/build'  # Adjust the path to your Ant build output
        ArtifactName: 'ant-build'
        publishLocation: 'Container'
