trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndPublish
  displayName: 'Build and Publish Flask App'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      cd python
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      python app.py
    displayName: 'Install Python Dependencies and Build'

  - task: ArchiveFiles@2
    displayName: 'Archive Flask App'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/flask-app.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'flask-app'
